apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-config
  labels:
    "app.kubernetes.io/name": "argocd"
    "app.kubernetes.io/instance": "argocd"
    group: {{ .Values.group | quote }}
data:
  ARGOCD_URL: {{ .Values.url | quote }}
