{{- if .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-access
  labels:
    "app.kubernetes.io/name": "argocd"
    "app.kubernetes.io/instance": "argocd"
    group: {{ .Values.group | quote }}
type: Opaque
stringData:
  ARGOCD_PASSWORD: {{ .Values.password | quote }}
  ARGOCD_USER: {{ .Values.username | quote }}
{{- end }}
